# Generated by Django 5.2.13 on 2026-04-25 15:26

from django.db import migrations, models


def copy_category_to_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.exclude(category_id__isnull=True).only('id', 'category_id'):
        product.categories.add(product.category_id)


def copy_categories_to_category(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.all().prefetch_related('categories'):
        first_category = product.categories.first()
        if first_category:
            product.category_id = first_category.id
            product.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.category'),
        ),
        migrations.RunPython(copy_category_to_categories, copy_categories_to_category),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
